name: sleep_module
services:
  sleep_module:
    container_name: sleep_module
    image: ${IMAGE}
    build:
      context: .
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    volumes:
      - ./src:/home/app/sleep_module/src
      - ./tests:/home/app/sleep_module/tests
    env_file: .env
    command: python -m sleep_rest_node --port 2000
    ports:
      - 2000:2000
